version: '3.8'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    networks:
      - pyChat-network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - ollama
    environment:
      - MONGO_URI=${MONGO_URI}
      - OLLAMA_URI=${OLLAMA_URI}
    networks:
      - pyChat-network

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - pyChat-network

volumes:
  ollama:

networks:
  pyChat-network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"